### ISSUE TITLE
wrong user and group in www.conf

### ISSUE THREAD

**Issue by webarchitect609** [chusiang/php7.ansible.role#6]
You forgot to change `user` and `group` in default pool `/etc/php/7.0/fpm/pool.d/www.conf`. This leads php-fpm to run from `www-data`. Not `vagrant` if I set `php_owner` role variable and so php can not write a file to htdocs.

**Comment by chusiang** [comment]
Hi @webarchitect609,

Can you providing more info, like ubuntu 14.04 or CentOS 6? 

Thank you.

**Comment by webarchitect609** [comment]
Ubuntu 14.04 LTS as a vagrant box `ubuntu/trusty64`. 

Same problem resolved by geerlingguy in such manner: 

> Specific settings inside the default www.conf PHP-FPM pool. If you'd like to manage additional settings, you can do so either by replacing the file with your own template or using lineinfile like this role does inside tasks/configure.yml.

Source: https://github.com/geerlingguy/ansible-role-php

**Comment by chusiang** [comment]
I find the problem, I will create a bug fix, thanks.

- Error log.

  ```
  # Ubuntu 14.04
  $ tail -f /var/log/syslog
  ...
  init: php7.0-fpm main process (3586) terminated with status 78
  php7.0-fpm respawning too fast, stopped ubuntu
  ...
  ```

- Origin `/etc/php/7.0/fpm/pool.d/www.conf`.

  ```
  ; listen.owner = xxx
  ; listen.group = xxx
  ```

- Now `/etc/php/7.0/fpm/pool.d/www.conf`.

  ```
  listen.owner = www-data
  listen.group = www-data
  ```

----

Manual testing with vagrant, before push commit.
 - [x] Ubuntu 14.04.
 - [x] Debian 8.
 - [x] CentOS 6
 - [x] CentOS 7
