### ISSUE TITLE
make upload_tmp_dir a var

### ISSUE THREAD

**Issue by rgarrigue** [chusiang/php7.ansible.role#7]
Hi

Imho upload_tmp_dir should be a var.

Thanks for the role,

**Comment by chusiang** [comment]
Hi @rgarrigue ,

I am busy, now.
I will add this feature at next week or later.

Thank you.

**Comment by chusiang** [comment]
Testing for this issue.

> https://travis-ci.org/chusiang/php7.ansible.role/builds/201079486

**Comment by chusiang** [comment]
I will release the v1.2.9 for this issue, thank you.

**Comment by rgarrigue** [comment]
Thanks !

2017-02-13 11:37 GMT+01:00 Chu-Siang Lai <notifications@github.com>:

**Comment by chusiang** [comment]
You are welcome. :+1:
